### ISSUE TITLE
SibcheStoreKit couldn't load price correctly

### ISSUE THREAD

**Issue by mohamadrezakoohkan** [sibche/SibcheStoreKit#3]
### Issue
I created a `SibcheSubscriptionPackage` with price of 25000 Toman from sibche developer platform and in client SDK i tried to fetch and purchase this package. Data was fetched successfully and the received `SibcheSubscriptionPackage` object has the valid price of 25.000 Toman.

```swift
_packageId = 0xd7e6c07e19409dfa "1135"
_type = 0x0000600003bf54a0 "SubscriptionInAppPackage"
_code = 0xd1c0574a0d45d9a9 "testsib"
_name = 0xd7e6c07a0d45d9aa "test"
_packageDescription = 0x000060000346e6c0 "nothing to see"
_price = 0xc7e6c07d4a75946d Int64(25000)
_totalPrice = 0xc7e6c07d4a75946d Int64(25000)
_discount = 0xc7e6c07d4a738eed Int64(0)
_duration = 0xc7e6c07d5460b6ed Int64(31536000)
_group = 0xd722e04fab73bea7 "subs-test"
```
The problem was the UI in the SDK showing price of 0 Toman instead of actual price.

<img width="350" alt="Screen Shot 1399-02-06 at 13 53 14" src="https://user-images.githubusercontent.com/37219076/80278726-4aed3c80-8701-11ea-8fcf-26176029d66e.png">

### Test Data
- SibcheStoreKit 4.1.2
- Xcode 11.3
- iOS 13.3
- iPhone Simulator

- Cocoapods 1.8.4

**Comment by mehdihz** [comment]
Your screenshot picture is related to your invoice and your invoice got 0 prices because your phone number has a **developer** or **tester** role in our system.
Please try to pay with another phone number and let me know if you face this problem again.

I'm closing this issue but feel free to open it again if your problem not fixed.

**Comment by mohamadrezakoohkan** [comment]
Is it possible to turn-off this annoying feature? because we need to be sure on production enviroment.

**Comment by mehdihz** [comment]
Yes I requested from backend guys to remove this feature.
Will let you know when done. But you can already test with another cellphone number and you can have your task done 👍
